#!/usr/bin/env python

import sys
from Bio import SeqIO

def main():
    ids = sys.argv[1:]
    records = SeqIO.to_dict(SeqIO.parse(sys.stdin, 'fasta'))
    SeqIO.write([records[id] for id in ids], sys.stdout, 'fasta')

if __name__ == '__main__':
    sys.exit(main())
